# PROBLEM 1

To find the product AB, we multiply corresponding elements of rows in matrix A with columns in matrix B and sum the products.

The resulting matrix C (A * B) will be a 3x3 matrix.

Let's calculate the elements of matrix C:
C[0,0] = (-1 * 0) + (2 * 0) + (3 * 2) = 0 + 0 + 6 = 6

C[0,1] = (-1 * 2) + (2 * 2) + (3 * 9) = -2 + 4 + 27 = 29

C[0,2] = (-1 * 1) + (2 * -8) + (3 * -1) = -1 - 16 - 3 = -20

C[1,0] = (4 * 0) + (-5 * 0) + (6 * 2) = 0 + 0 + 12 = 12

C[1,1] = (4 * 2) + (-5 * 2) + (6 * 9) = 8 - 10 + 54 = 52

C[1,2] = (4 * 1) + (-5 * -8) + (6 * -1) = 4 + 40 - 6 = 38

C[2,0] = (7 * 0) + (8 * 0) + (-9 * 2) = 0 + 0 - 18 = -18

C[2,1] = (7 * 2) + (8 * 2) + (-9 * 9) = 14 + 16 - 81 = -51

C[2,2] = (7 * 1) + (8 * -8) + (-9 * -1) = 7 - 64 + 9 = -48

therefore, the matrix product of matrices A and B (AB) is:
    
    C = [6   29   -20 ]
    
        [12   52    38]
        
        [-18    -51   -48]

# PROBLEM 2

In [1]:
import numpy as np

# Define matrices A and B using NumPy arrays
A = np.array([[-1, 2, 3],
              [4, -5, 6],
              [7, 8, -9]])

B = np.array([[0, 2, 1],
              [0, 2, -8],
              [2, 9, -1]])

# Method 1: Using np.matmul()
result_matmul = np.matmul(A, B)

# Method 2: Using np.dot()
result_dot = np.dot(A, B)

# Method 3: Using the @ operator
result_operator = A @ B

# Display the results
print("Result using np.matmul():")
print(result_matmul)

print("\nResult using np.dot():")
print(result_dot)

print("\nResult using @ operator:")
print(result_operator)

Result using np.matmul():
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Result using np.dot():
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Result using @ operator:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# PROBLEM 3

In [5]:
import numpy as np

# Define matrices A and B using NumPy arrays
A = np.array([[-1, 2, 3],
              [4, -5, 6],
              [7, 8, -9]])

B = np.array([[0, 2, 1],
              [0, 2, -8],
              [2, 9, -1]])

# Function to perform matrix multiplication
def matrix_multiplication(mat1, mat2):
    result = np.zeros((mat1.shape[0], mat2.shape[1]))

    for i in range(mat1.shape[0]):
        for j in range(mat2.shape[1]):
            for k in range(mat1.shape[1]):
                result[i, j] += mat1[i, k] * mat2[k, j]

    return result

# Calculate the matrix product without using NumPy's functions
result_manual = matrix_multiplication(A, B)

# Display the result
print("Result of matrix multiplication without using NumPy's functions:")
print(result_manual)

Result of matrix multiplication without using NumPy's functions:
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# PROBLEM 4

The matrix product DE is defined when the number of columns of D is equal to the number of rows of E, so it cannot be calculated in this example.

# PROBLEM 5

In [7]:
import numpy as np

# Define matrices D and E using NumPy arrays
D = np.array([[-1, 2, 3],
              [4, -5, 6]])

E = np.array([[-9, 8, 7],
              [6, -5, 4]])

# Function to perform matrix multiplication
def matrix_multiplication(mat1, mat2):
    if mat1.shape[1] != mat2.shape[0]:
        print("Error: Matrix multiplication cannot be performed due to incompatible shapes.")
        print(f"Matrix D shape: {mat1.shape}, Matrix E shape: {mat2.shape}")
        return None

    result = np.zeros((mat1.shape[0], mat2.shape[1]))

    for i in range(mat1.shape[0]):
        for j in range(mat2.shape[1]):
            for k in range(mat1.shape[1]):
                result[i, j] += mat1[i, k] * mat2[k, j]

    return result

# Calculate the matrix product with check for matrix dimensions
result = matrix_multiplication(D, E)

# Display the result or error message
if result is not None:
    print("Result of matrix multiplication:")
    print(result)

Error: Matrix multiplication cannot be performed due to incompatible shapes.
Matrix D shape: (2, 3), Matrix E shape: (2, 3)


# PROBLEM 6 Transposition

In [6]:
# Transpose the result obtained from manual multiplication
transposed_result = np.transpose(result_manual)  # or transposed_result = result_manual.T

# Calculate the matrix product of transposed matrix with itself
product_of_transposed = np.matmul(transposed_result, transposed_result)

# Display the transposed matrix and its matrix product
print("Transposed matrix:")
print(transposed_result)

print("\nMatrix product of the transposed matrix with itself:")
print(product_of_transposed)

Transposed matrix:
[[  6.  12. -18.]
 [ 29.  52. -51.]
 [-20.  38. -48.]]

Matrix product of the transposed matrix with itself:
[[ 744.   12.  144.]
 [2702. 1114. -726.]
 [1942.  -88.  726.]]
